import firebaseConfig from "./Config/FirebaseConfig";
import { getAuth } from "firebase/auth";
import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";
const FireBaseApp = initializeApp(firebaseConfig);
const auth = getAuth(FireBaseApp);
const db = getFirestore(FireBaseApp);
const storage = getStorage(FireBaseApp);
export { auth, db, storage };
